const FONT_FAMILY = {
  COM_BD: 'Comfortaa-Bold',
  COM_MD: 'Comfortaa-Medium',
  COM_RG: 'Comfortaa-Regular',
  COM_SB: 'Comfortaa-SemiBold',
  MON_XB: 'Montserrat-ExtraBold',
  MON_BD: 'Montserrat-Bold',
  MON_MD: 'Montserrat-Medium',
  MON_RG: 'Montserrat-Regular',
  MON_SB: 'Montserrat-SemiBold',
  POP_BD: 'Poppins-Bold',
  POP_XB: 'Poppins-ExtraBold',
  POP_MD: 'Poppins-Medium',
  POP_RG: 'Poppins-Regular',
  POP_SB: 'Poppins-SemiBold',
};

const COMFORTAA = {
  b: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.COM_BD},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.COM_BD},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.COM_BD},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.COM_BD},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.COM_BD},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.COM_BD},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.COM_BD},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.COM_BD},
  },
  reg: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.COM_RG},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.COM_RG},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.COM_RG},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.COM_RG},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.COM_RG},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.COM_RG},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.COM_RG},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.COM_RG},
  },
  sb: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.COM_SB},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.COM_SB},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.COM_SB},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.COM_SB},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.COM_SB},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.COM_SB},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.COM_SB},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.COM_SB},
  },
  md: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.COM_MD},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.COM_MD},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.COM_MD},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.COM_MD},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.COM_MD},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.COM_MD},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.COM_MD},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.COM_MD},
  },
};

const MONTSERRAT = {
  b: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.MON_BD},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.MON_BD},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.MON_BD},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.MON_BD},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.MON_BD},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.MON_BD},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.MON_BD},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.MON_BD},
  },
  xb: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.MON_XB},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.MON_XB},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.MON_XB},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.MON_XB},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.MON_XB},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.MON_XB},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.MON_XB},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.MON_XB},
  },
  reg: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.MON_RG},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.MON_RG},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.MON_RG},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.MON_RG},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.MON_RG},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.MON_RG},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.MON_RG},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.MON_RG},
  },
  sb: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.MON_SB},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.MON_SB},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.MON_SB},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.MON_SB},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.MON_SB},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.MON_SB},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.MON_SB},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.MON_SB},
  },
  md: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.MON_MD},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.MON_MD},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.MON_MD},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.MON_MD},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.MON_MD},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.MON_MD},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.MON_MD},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.MON_MD},
  },
};

const POPPINS = {
  b: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.POP_BD},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.POP_BD},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.POP_BD},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.POP_BD},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.POP_BD},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.POP_BD},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.POP_BD},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.POP_BD},
  },
  xb: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.POP_XB},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.POP_XB},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.POP_XB},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.POP_XB},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.POP_XB},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.POP_XB},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.POP_XB},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.POP_XB},
  },
  reg: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.POP_RG},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.POP_RG},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.POP_RG},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.POP_RG},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.POP_RG},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.POP_RG},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.POP_RG},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.POP_RG},
  },
  sb: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.POP_SB},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.POP_SB},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.POP_SB},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.POP_SB},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.POP_SB},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.POP_SB},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.POP_SB},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.POP_SB},
  },
  md: {
    pt12: {fontSize: 12, fontFamily: FONT_FAMILY.POP_MD},
    pt13: {fontSize: 13, fontFamily: FONT_FAMILY.POP_MD},
    pt14: {fontSize: 14, fontFamily: FONT_FAMILY.POP_MD},
    pt16: {fontSize: 16, fontFamily: FONT_FAMILY.POP_MD},
    pt18: {fontSize: 18, fontFamily: FONT_FAMILY.POP_MD},
    pt20: {fontSize: 20, fontFamily: FONT_FAMILY.POP_MD},
    pt24: {fontSize: 24, fontFamily: FONT_FAMILY.POP_MD},
    pt32: {fontSize: 32, fontFamily: FONT_FAMILY.POP_MD},
  },
};

const FONTFAMILY = {
  COMFORTAA,
  MONTSERRAT,
  POPPINS,
};

export default FONTFAMILY;
